# Generated by Django 5.1.7 on 2025-03-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
    ]
