# Generated by Django 5.1.7 on 2025-03-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20250310_1200'),
    ]

    operations = [
    ]
