# Generated by Django 5.1.7 on 2025-03-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20250310_1258'),
    ]

    operations = [
    ]
