# Generated by Django 5.1.7 on 2025-03-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_auto_20250310_1331'),
    ]

    operations = [
    ]
