# Generated by Django 5.1.7 on 2025-03-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_auto_20250311_0911'),
    ]

    operations = [
    ]
