# Generated by Django 5.1.7 on 2025-03-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0017_auto_20250311_1004'),
        ('weather', '0019_auto_20250311_1101'),
    ]

    operations = [
    ]
