# Generated by Django 5.1.7 on 2025-03-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0021_auto_20250311_1115'),
    ]

    operations = [
    ]
