# Generated by Django 5.1.7 on 2025-03-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0025_auto_20250311_1239'),
    ]

    operations = [
    ]
