# Generated by Django 5.1.7 on 2025-03-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0026_auto_20250311_1243'),
    ]

    operations = [
    ]
