# Generated by Django 5.1.7 on 2025-03-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0027_auto_20250311_1251'),
    ]

    operations = [
    ]
