# Generated by Django 5.1.7 on 2025-03-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0028_auto_20250311_1318'),
    ]

    operations = [
    ]
