# Generated by Django 5.1.7 on 2025-03-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0029_auto_20250311_1322'),
    ]

    operations = [
    ]
