# Generated by Django 5.1.7 on 2025-03-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0033_auto_20250311_1342'),
    ]

    operations = [
    ]
