# Generated by Django 5.1.7 on 2025-03-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0034_auto_20250311_1345'),
    ]

    operations = [
    ]
