# Generated by Django 5.1.7 on 2025-03-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0035_auto_20250311_1353'),
        ('weather', '0036_auto_20250311_1352'),
    ]

    operations = [
    ]
