# Generated by Django 5.1.7 on 2025-03-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0037_merge_0035_auto_20250311_1353_0036_auto_20250311_1352'),
    ]

    operations = [
    ]
