# Generated by Django 5.1.7 on 2025-03-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0042_auto_20250311_1430'),
    ]

    operations = [
    ]
