# Generated by Django 5.1.7 on 2025-03-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0043_auto_20250311_1442'),
    ]

    operations = [
    ]
