# Generated by Django 5.1.7 on 2025-03-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0044_auto_20250311_1455'),
    ]

    operations = [
    ]
