# Generated by Django 5.1.7 on 2025-03-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0045_auto_20250311_1510'),
    ]

    operations = [
    ]
