# Generated by Django 5.1.7 on 2025-03-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0046_auto_20250312_1130'),
    ]

    operations = [
    ]
