# Generated by Django 5.1.7 on 2025-03-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0046_auto_20250319_1010'),
        ('weather', '0047_auto_20250314_1339'),
    ]

    operations = [
    ]
