# Generated by Django 5.1.7 on 2025-03-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0048_merge_0046_auto_20250319_1010_0047_auto_20250314_1339'),
    ]

    operations = [
    ]
