# Generated by Django 5.1.7 on 2025-03-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0049_auto_20250319_1114'),
    ]

    operations = [
    ]
