# Generated by Django 5.1.7 on 2025-03-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0051_auto_20250321_1139'),
    ]

    operations = [
    ]
